print("-AADI'S ARCADE-")
print("")
name = input("Name: ")
if name == "Aadi":
    print("")
    print("Welcome creator.")
print("")
print("select a text based game to continue")
print("invalid response will require re-running the program")
print("")
print("1. ROCK-PAPER-SCISSORS")
print("")
print("2. SWORD IN THE STONE")
print("")
print("(1/2)")
print("")
game_select = input("Game: ")
print("")
if game_select == "1":
    print("-GAME SELECTED-")
    print("")
    print("ROCK-PAPER-SCISSORS")
    print("")
    print("So, you want to play a game do you",name,"?")
    print("")
    print("(yes/no)")
    print("")
    rps_game_yn = input("")
    print("")
    print("Well it doesn't matter what you selected your playing this game now!")
    print("Oh and by the way, it's best of one. So there is no coming back if you lose a round.")
    print("I shall let you go first:")
    print("")
    print("(rock/paper/scissors)")
    print("")
    rps_selection = input()
    print(" ")
    if rps_selection == "rock":
        print("paper")
        print(" ")
        print("That's a WRAP folks!")
        print(" ")
        print("-YOU LOSE-")
    elif rps_selection == "paper":
        print("scissors")
        print(" ")
        print("Aaaand, CUT!")
        print(" ")
        print("-YOU LOSE-")
    elif rps_selection == "scissors":
        print("rock")
        print(" ")
        print("SMASHED right through to victory!")
        print(" ")
        print("-YOU LOSE-")
    elif rps_selection == "gun":
        print("scissors")
        print(" ")
        print("...")
        print("Wait.")
        print("No.")
        print(" ")
        print("-YOU WIN-")
    elif rps_selection == "lizard":
        print("rock")
        print(" ")
        print("Animal protection laws? What are those?")
        print("Who are all these people?")
        print("Wait where are thay taking me?")
        print(" ")
        print("-ANIMAL CRUELTY-")
    elif rps_selection == "sword":
        print("scissors")
        print(" ")
        print("Why is yours so much bigger than mine?")
        print("That's not fair.")
        print(" ")
        print("-EMOTIONAL DAMAGE-")
    elif rps_selection == "grenade":
        print("paper")
        print(" ")
        print("Well this is not gonna do much.")
        print("Taking me down with you huh?")
        print("Or did you think you would somehow survive a grenade blast?")
        print(" ")
        print("-MUTUAL DISTRUCTION-")
    elif rps_selection == "boo":
        print("AAH!")
        print(" ")
        print("...")
        print(" ")
        print("-HEART ATTACK-")
    elif rps_selection == "fire":
        print("water")
        print(" ")
        print("Nope, we are not recreating the events at the amazon rainforest here.")
        print(" ")
        print("-FIRE SAFETY LESSON-")
    elif rps_selection == "0":
        print("1")
        print(" ")
        print("1 is more than 0 las01110100 I che0110001101101011011001010110010000001010")
        print(" ")
        print("H0110010101101100P")
        print("01101001t 0110100001110101r0111010001110011")
        print("011101110110100001100001011101000010000001101000011000010111011001100101001000000111100101101111011101010010000001100100011011110110111001100101")
        print(" ")
        print("-CO01110010R01110101PT01100101D-")
    else:
        print("You are hopeless.")
        print(" ")
        print("-SHAME-")
    print("")
    print("this game has 9 endings")
    print("")
    keep_open = input()
elif game_select == "2":
    print("unfinished")
